version: "3.9"

services:
  xsearch:
    image: ${IMAGE}
    pull_policy: never
    restart: always
    volumes:
      - ${DATA_PATH}:/reference_data
    expose:
      - "{PORT}"
    ports:
      - "{PORT}:8081"
    env_file:
      - .env
    networks:
      - xpcr

networks:
  xpcr:
    driver: bridge
    ipam:
      driver: default
    name: prc_network
