version: '3'
services:
  cloud-pacs-primer:
    build:
      dockerfile: dockerfiles/Dockerfile.primer.dev
      context: ./
    image: cloud-pacs-primer:dev
    container_name: cloud-pacs-primer
    restart: always
    ports:
      - 9516:9516
    environment:
      - JVM_XMS=256m
      - JVM_XMX=1024m
      - JVM_XMN=256m
      - SPRING_PCR_MYSQL_URL=jdbc:mysql://pcr_mysql/?useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      - SPRING_PCR_MYSQL_USERNAME=root
      - SPRING_PCR_MYSQL_PASSWORD=mgix@com
    volumes:
      - ./logs:/bgi/logs
    networks:
      - prc_network

networks:
  prc_network:
    external: true